### ISSUE TITLE
無視ユーザーのオプション追加

### ISSUE THREAD

**Issue by mana544** [mana544/check-pr-ref-name#4]
GH ActionsボットによるEditイベントを無視したい
イベントトリガー時のペイロードオブジェクト "sender.login" が"github-actions" の場合は無視できそう。

**Comment by mana544** [comment]
## アイデアメモ
ユーザログイン名による無視じゃなくて、イベントのアクションランナーIDを引っ張れないか？
そうすれば、actions一律無視ではなくて、「ある特定のアクションは無視」ってできる。

**Comment by mana544** [comment]
## コンテキストから引っ張れる情報
たとえば、以下のような ワークフローだとして。 `.github/workflows/main.yml`

```yaml
on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: this action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          in-put: 'なんか入力'

```

### `context.workflow`
呼び出されたワークフローファイル名。
例: `'.github/workflows/main.yml'`

### `context.action`
呼び出されたアクションステップのid。
ワークフローYAMLの `jobs.<job-id>.steps[*].id` の value。
例: `'hello'`

### `context.job`
呼び出されたワークフローjob ID。
ワークフローYAMLの `jobs.<job-id>` の `<job-id>` 部分
例: `'hello_world_job'`
